### ISSUE TITLE
Запуск бота на docker

### ISSUE THREAD

**Issue by instant992** [bomzheg/KarmaBot#103]
Подскажите, а есть ли свежая инструкция по распаковке бота на docker? Ибо по той инструкции которая сейчас есть, выдаются ошибки.

**Comment by bomzheg** [comment]
без описания ошибок - ничего не понятно

**Comment by instant992** [comment]
![photo_2023-02-17_18-52-50](https://user-images.githubusercontent.com/59600183/219899354-9671be69-19ab-43da-b82b-996e0a3d945f.jpg)
Вот такая ошибка была, делал по той инструкции, поставил питон 3.10 еще

**Comment by bomzheg** [comment]
https://github.com/bomzheg/KarmaBot/blob/master/config_dist/.env#L10
полагаю такая переменная окружения не установлена

**Comment by instant992** [comment]
![Screenshot_48](https://user-images.githubusercontent.com/59600183/219900130-310926e9-d86d-49c9-aac4-dfaf2a8ba776.png)
![Screenshot_49](https://user-images.githubusercontent.com/59600183/219900131-19fbbdbc-a255-4fb7-9c90-1ca8d55a6e91.png)
Ну я пробовал оставлять и стандартное, и переделывать на mysql, ошибка одна и та же была, значение в этом файле стоит, возможно дополнить чем то надо это значение?

**Comment by bomzheg** [comment]
не прокинулась переменная окружения в контейнер. хз почему

**Comment by instant992** [comment]
И что можно сделать что бы оно заработало?

**Comment by bomzheg** [comment]
![image](https://github.com/bomzheg/KarmaBot/assets/3669045/d4e58b28-6cf8-439b-b9e8-aa2ebb9ce9f6)

у меня примерно такие же настройки.

компоуз:
![image](https://github.com/bomzheg/KarmaBot/assets/3669045/ef8d8e4e-4f76-4023-8bfb-66bf8807e596)
