### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by Desiders** [bomzheg/KarmaBot#114]
Which code formatter preferably when write code in this repo?

I can use black, but it reformats a large amount of the code

**Comment by ruslan-korneev** [comment]
@Desiders i've tried black, but there is a lot of changes related to `' -> "`

there should be the way to format everything without touching that symbol

**Comment by bomzheg** [comment]
now i use no formatter for this repo, but probably black or ruff (as a formatter) will be ok
