### ISSUE TITLE
Remove karma abuse

### ISSUE THREAD

**Issue by F0rzend** [bomzheg/KarmaBot#65]
Игнорировать аргумент `n: int` у ±n, если пользователь не является админом и его карма ниже 500

Данный функционал приносит в чат разногласия и своеобразные "войны". Даже когда человек действительно очень помог, рассказал что-то новое, интересное, ему дают +1, чтобы он не оторвался далеко в топе юзеров по карме

**Comment by bomzheg** [comment]
почему именно 500? думаю рано или поздно, возможно к концу года топ30 питонистов будут иметь 500+ кармы. а в других чатах с меньшей активностью 500 может ещё пять лет будет набираться.
критерии нужны более четкие и не зависеть от масштаба

**Comment by 0Kit** [comment]
> почему именно 500? думаю рано или поздно, возможно к концу года топ30 питонистов будут иметь 500+ кармы. а в других чатах с меньшей активностью 500 может ещё пять лет будет набираться.
> критерии нужны более четкие и не зависеть от масштаба

Тогда как насчёт ⅔ от среднего арифметического 15 первых в топе

**Comment by bomzheg** [comment]
я бы сказал, что мне не нравится, но давай спросим у коллег
@k4m454k @bth2008 @jorektheglitch

**Comment by 0Kit** [comment]
Можно просто первым 7и дать

**Comment by atlas17** [comment]
Кто-то пишет +1 от своих 5, а кто-то плюсует полностью на >30. Карма в обе стороны работает, поведение каждого видно.
Введение плюсов на полшишечки решало конкретную проблему: иногда хочется плюсануть за какую-то мелочь, или шутку, когда полновесный плюс явно перебор. Такая ситуация может возникнуть и у людей с кармой меньше N.
К тому же любые кармовые пороги часто провоцируют желание их достигнуть. Против.

**Comment by bomzheg** [comment]
Отклонено.
